name: Kittygram CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  backend_checks:
    name: Backend ruff + pytest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install ruff pytest

      - name: Ruff
        run: ruff check backend

      - name: Pytest
        run: |
          cd backend
          pytest || [ $? -eq 5 ]

  frontend_tests:
    name: Frontend tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Run tests
        working-directory: frontend
        env:
          CI: "true"
        run: npm test -- --watchAll=false

  build_and_push:
    name: Build & Push images
    runs-on: ubuntu-latest
    needs: [backend_checks, frontend_tests]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest

      - name: Build & push gateway
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest

  notify:
    name: Telegram notify
    runs-on: ubuntu-latest
    needs: build_and_push
    if: success()

    steps:
      - name: Send message
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ Kittygram CI/CD успешно выполнен
